service: nest-birrita

useDotenv: true

package:
  individually: true
  excludeDevDependencies: false

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_EXPIRATION_TIME: ${env:JWT_EXPIRATION_TIME}
    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY}
    AUTH_REDIRECT_URI: ${env:AUTH_REDIRECT_URI}

functions:
  dispenser:
    handler: dist/apps/dispenser/main.handler
    events:
      - http:
          method: POST
          path: dispenser
    package:
      patterns:
        - dist/apps/dispenser/**